name = "SubmodTree"
uuid = "21cdea2c-a507-4bac-b7db-f3a680eabb41"
authors = ["anand jain <anandj@uchicago.edu>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
